<?php

/**
 * crpTalk
 *
 * @copyright (c) 2009, Daniele Conca
 * @link http://code.zikula.org/crptalk Support and documentation
 * @author Daniele Conca <conca.daniele@gmail.com>
 * @license GNU/GPL - v.2.1
 * @package crpTalk
 */

/**
 * crpTalkUI Object
 */
class crpTalkUI
{

	function crpTalkUI()
	{
		//
	}

	/**
	 * draw modify configuration form
	 *
	 * @param array $modvars module's variables
	 *
	 * @return string html
	 */
	function modifyConfig($modvars= array (), $gdArray= array ())
	{
		// Create output object
		$pnRender= pnRender :: getInstance('crpTalk', false);

		$pnRender->assign($modvars);

		// Return the output that has been generated by this function
		return $pnRender->fetch('crptalk_admin_modifyconfig.htm');
	}

	/**
	 * draw widget form
	 *
	 * @param array $modvars module's variables
	 *
	 * @return string html
	 */
	function displayWidget($modvars= array ())
	{
		// Create output object
		$pnRender= pnRender :: getInstance('crpTalk');

		$pnRender->assign($modvars);

		// Return the output that has been generated by this function
		return $pnRender->fetch('crptalk_user_display.htm');
	}

}